# Generated by Django 3.1.7 on 2021-03-28 13:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210326_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
