# Generated by Django 3.1.7 on 2021-04-10 14:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_faq_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='services',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
