# Generated by Django 3.1.7 on 2021-03-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210324_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='Category',
        ),
    ]
