# Generated by Django 3.1.7 on 2021-03-30 15:02

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210330_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category'),
        ),
    ]
