# Generated by Django 3.1.7 on 2021-03-31 14:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210331_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.content'),
        ),
    ]
