# Generated by Django 3.1.7 on 2021-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210331_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
