# Generated by Django 3.1.7 on 2021-04-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='content',
        ),
    ]
