# Generated by Django 3.1.7 on 2021-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_remove_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
