# Generated by Django 3.1.7 on 2021-04-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
    ]
