# Generated by Django 3.1.7 on 2021-04-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210411_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
    ]
