# Generated by Django 3.1.7 on 2021-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_remove_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
