# Generated by Django 3.1.7 on 2021-04-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_content_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title2',
        ),
    ]
