# Generated by Django 3.1.7 on 2021-04-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_kjhds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KJHDS',
        ),
    ]
